site_name: PySQLXEngine

site_description: Python Async SQL Engines

site_url: "https://github.com/carlos-rian/pysqlx-engine"

theme:
  name: material
  font:
    code: Roboto Mono

  palette:
    - scheme: default
      primary: black
      accent: orange
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

    - scheme: slate
      primary: black
      accent: orange
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

  features:
    - search.suggest
    - search.highlight
    - search.share
    - search.suggest

    - navigation.indexes
    - navigation.top
    - navigation.instant
    - navigation.tracking
    - header.autohide

    - navigation.tabs
    - navigation.footer

    - content.code.copy
    - content.code.annotate

  icon:
    repo: fontawesome/brands/github
  logo: img/favicon/icon.png
  favicon: img/favicon/favicon.ico
  language: en

repo_name: "carlos-rian/pysqlx-engine"

repo_url: "https://github.com/carlos-rian/pysqlx-engine"

plugins:
  - search
  - mkdocs-video:
      mark: "custom-marker"

  - glightbox

nav:
  - Home: index.md

  - User Guide:
      - user_guide/index.md
      - Database Connectors:
          - PostgreSQL: user_guide/uri_postgresql.md
          - MySQL: user_guide/uri_mysql.md
          - SQLite: user_guide/uri_sqlite.md
          - Microsoft SQL Server:
              - user_guide/sqlserver/index.md
              - Microsoft SQL Server Windows (Local): user_guide/uri_sqlserver_windows.md
              - Microsoft SQL Server on Docker: user_guide/uri_sqlserver_docker.md

      - Examples: user_guide/examples.md
      - Queries: user_guide/queries.md
      - Documentation for Methods: user_guide/extras.md

  - Advanced Guide:
      - DML with return: advanced_guide/dml_with_return.md
      - Simple Pool With Concurrent Connections: advanced_guide/simple_pool_conn.md

  - Type Mappings: type_mappings.md
  - Supported Databases: databases_and_versions.md
  - Core: core_engine.md

markdown_extensions:
  - tables
  - toc:
      permalink: true
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown_include.include:
      base_path: docs
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - admonition
  - attr_list
  - extra
  - pymdownx.smartsymbols
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_div_format
  - pymdownx.tabbed:
      alternate_style: true

copyright: Copyright &copy; 2022 - 2023 Carlos Rian

extra_css:
  - css/termynal.css
  - css/custom.css
  #- css/extras.css

extra_javascript:
  - https://unpkg.com/mermaid@8.4.6/dist/mermaid.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/tablesort/5.2.1/tablesort.min.js
  - js/termynal.js
  - js/custom.js
  #- js/table.js
