name: CI

on:
  push:
    branches:
      - main
      - release/*

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 4
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]
      fail-fast: false

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: enable cache
        uses: actions/cache@v3
        id: cache
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ runner.os }}-python-${{ env.pythonLocation }}-${{ hashFiles('pyproject.toml') }}-test-v02

      - name: up database
        run: cp tests/docker/docker-compose.yml docker-compose.yml &&
          docker-compose up --build --detach

      - name: wait container up
        run: |
          docker ps -a && \
          sleep 20

      - name: install poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.1.12
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: install python dependencies
        run: poetry install --no-interaction
        if: steps.cache-deps.outputs.cache-hit != 'true'

      - name: run unittest
        run: poetry run pytest --ignore=tests/benchmark --cov=pysqlx_engine --cov=tests --cov-report=term-missing:skip-covered --cov-report=xml tests ${@}

      - name: upload coverage
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: ${{ matrix.os }}_${{ matrix.python-version }}_date '+%Y-%m-%d %H:%M'

  build:
    #if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: check package version
        run: |
          pip install --upgrade httpx toml
          python .github/check_version.py

      - name: build and publish to pypi
        uses: JRubics/poetry-publish@v1.13
        with:
          pypi_token: ${{ secrets.PYPI_TOKEN }}
