name: Publish Github Pages

on:
  push:
    branches:
      - main
    paths:
      - '**.md'
      - '**.css'
      - '**.js'
      - '**.png'
      - 'docs/*'
      - 'mkdocs.yml'
      - 'pyproject.toml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.10.0
      - run: pip install -r requirements-dev.txt 
      - run: mkdocs gh-deploy --force