# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Upload Python Package

#on:
#  release:
#    types: [published]
on: [push]

permissions:
  contents: read

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'

    - name: Update PIP
      run: |
        python -m pip install --upgrade pip

    - name: Install Poetry
      run: python -m pip install --user poetry

      
    - name: Install dependences
      run: python -m poetry install --no-dev

    - name: Export envs
      run: |
        export POETRY_PYPI_TOKEN_PYPI=${{ secrets.PYPI_API_TOKEN }}
        export POETRY_HTTP_BASIC_PYPI_USERNAME="carlos.rian"
        export POETRY_HTTP_BASIC_PYPI_PASSWORD=${{ secrets.PYPI_PASSWORD }}
        
    - name: Build package
      run: python -m poetry build
    
    - name: Publish package
      run: python -m poetry publish
