name: Unit Test Run and Publish

on:
  push:
    branches:
      - 'main'
      - 'dependabot*'
    paths:
      - '/sqlx_engine/*'
      - '/tests/*'
      - 'requirements*'
      - 'pyproject.toml'
      - '.github/workflows/unittest.yml'

jobs:
  test:
    name: Run Unit Test
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 1
      matrix:
        # os: [ubuntu-latest, windows-2019, windows-latest]
        os: [windows-2019]
        #python-version: ["3.8", "3.9", "3.10"]
        python-version: ["3.8"]
      fail-fast: true

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          
      - uses: actions/cache@v2
        id: cache
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ runner.os }}-python-${{ env.pythonLocation }}-${{ hashFiles('pyproject.toml') }}-test-v02


      - name: Up Database
        run: |
          docker run -e ACCEPT_EULA=Y -e SA_PASSWORD=Build!Test321 -p 4444:1433 -d mcr.microsoft.com/mssql/server:2019-latest && \
          # docker run -e MYSQL_DATABASE=engine -e MYSQL_ROOT_PASSWORD=Build!Test321 -p 4443:3306 -d --platform {{ matrix.os }} mysql:latest && \
          # docker run -e POSTGRES_DB=engine -e POSTGRES_PASSWORD=Build!Test321 -p 4442:5432 -d --platform {{ matrix.os }} postgres:latest
      
      - name: Check Containers
        run: |
          docker ps -a && \
          sleep 20

      - name: Poetry Install and Export
        run: |
          pip install poetry --user && \
          poetry export --dev -f requirements.txt --output requirements-dev.txt  --without-hashes
      
      - name: Install Dependencies
        run: pip install -r requirements-dev.txt
        
      - name: Test
        run: pytest --cov=sqlx_engine --ignore=tests --cov-report=term-missing:skip-covered --cov-report=xml tests ${@}
        
      - name: Upload coverage
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: pytest ${{ matrix.os }}-${{ matrix.python-version }}
