name: Unit Test Run and Publish

on:
  push:
    branches:
      - 'main'
      - 'dependabot*'
    paths:
      - '/sqlx_engine/*'
      - '/tests/*'
      - 'requirements*'
      - 'pyproject.toml'
      - '.github/workflows/unittest.yml'

jobs:
  test:
    name: Run Unit Test
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 1
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.8", "3.9", "3.10"]
      fail-fast: true

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          
      - uses: actions/cache@v2
        id: cache
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ runner.os }}-python-${{ env.pythonLocation }}-${{ hashFiles('pyproject.toml') }}-test-v02


      - name: Up Database
        run: docker-compose up --build --detach

      - name: Check Containers
        run: |
          docker ps -a && \
          sleep 20

      - name: Install Dependencies
        run: |
          pip install poetry --user && \
          poetry export --dev -f requirements.txt --output requirements-dev.txt  --without-hashes && \
          pip install -r requirements-dev.txt
        
      - name: Test
        run: pytest --cov=sqlx_engine --ignore=tests --cov-report=term-missing:skip-covered --cov-report=xml tests ${@}
        
      - name: Upload coverage
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: pytest ${{ matrix.os }}-${{ matrix.python-version }}
